#!/bin/bash
# GSM8K counterpart of run_final_3b_math_suite.sh -- same 9 algorithms, same hyperparameter choices
# validated on MATH this session (TRIBE: lr=1e-7/eps=0.5/chi_squared negfrac sweep; everything else lr=5e-7),
# applied to the existing self-generated GSM8K data (gsm8k-llama-boxed / gsm8k-llama-boxed-dpo-pairs --
# generated by this same Llama-3.2-3B-Instruct model, pre-dates this session's bug fixes but raw
# (prompt,completion,reward) data isn't touched by those fixes, only the training/save/eval path is).
#
# Batch size / deepspeed settings copied from this project's own established GSM8K-Llama convention
# (slurm/logs/offpolicy-*-llama-gsm8k-boxed-*.out), NOT copied from the MATH suite's settings -- GSM8K's
# much shorter completions (max 512 vs MATH's 1024) never needed ZeRO-3 sharding for most methods:
#   GRPO/TOPR/TIS/RLOO/NaiveReinforce/TRIBE: bs=8, no deepspeed, --mixed_precision=bf16
#   RAFT: bs=16, no deepspeed, --mixed_precision=bf16
#   DPO: bs=4/grad_accum=16, deepspeed zero3 (needed -- DPO's paired forward pass is heavier)
#   SimPO: bs=4/grad_accum=16, no deepspeed, --mixed_precision=bf16, cosine schedule
#
# divergence=chi_squared is mandatory for TRIBE, not a default -- kl_new_old confirmed dead this session
# (6/6 configs collapse to 0% accuracy on MATH, lambda pinned at solve_lambda's -50 safety clamp; same
# closed-form code path, so the same bug applies here).
#
# Every checkpoint gets scripts/overlay_base_config.py applied before eval, and eval is pass@1 (greedy) +
# pass@4 (num_generations=4, temperature=1.0, top_k=50) via scripts/eval_gsm8k.py --answer_format boxed
# (must match gsm8k-llama-boxed's own boxed format) on the actual GSM8K TEST split (1319 examples) --
# both handled by a Monitor loop outside this script, not submitted here.
#
# Usage: bash slurm/run_final_3b_gsm8k_suite.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOGDIR="$REPO_ROOT/slurm/logs"
MODEL="meta-llama/Llama-3.2-3B-Instruct"
DATASET=/scratch4/workspace/ychittepu_umass_edu-tribe/offpolicy-data/gsm8k-llama-boxed
DPO_DATASET=/scratch4/workspace/ychittepu_umass_edu-tribe/offpolicy-data/gsm8k-llama-boxed-dpo-pairs
OUTBASE=/scratch4/workspace/ychittepu_umass_edu-tribe/offpolicy-suite-final/final-3b-gsm8k
LAUNCH="accelerate launch --num_processes=2 --mixed_precision=bf16 --main_process_port=\$MASTER_PORT"

JOBLIST_FILE="$REPO_ROOT/slurm/final_3b_gsm8k_jobs.tsv"
: > "$JOBLIST_FILE"

submit_train() {
  local name="$1" script="$2" extra="$3" bs="${4:-8}"
  local outdir="${OUTBASE}/${name}/gsm8k"
  local cmd="$LAUNCH scripts/${script} --model_name_or_path ${MODEL} --dataset_path ${DATASET} \
    --output_dir ${outdir} --group_size 16 --per_device_train_batch_size ${bs} \
    --lr_scheduler_type constant \
    ${extra} --save_total_limit 1 --num_train_epochs 1 --gradient_checkpointing \
    --bf16 True --report_to wandb --run_name offpolicy-${name}-final-3b-gsm8k"
  local jid=$(sbatch --parsable --gpus=2 --mem=240G --time=1-00:00:00 \
    --job-name="offpolicy-${name}-final-3b-gsm8k" \
    --output="${LOGDIR}/offpolicy-${name}-final-3b-gsm8k-%j.out" \
    --error="${LOGDIR}/offpolicy-${name}-final-3b-gsm8k-%j.err" \
    --export=ALL,TRAIN_CMD="$cmd" \
    "$REPO_ROOT/slurm/run_experiment.sbatch")
  echo -e "${jid}\t${name}\t${outdir}\t${MODEL}" >> "$JOBLIST_FILE"
  echo "submitted $name: train=$jid"
}

submit_train "grpo"            "train_gsm8k_offpolicy_grpo.py"            "--learning_rate 5e-7"
submit_train "topr"            "train_gsm8k_offpolicy_topr.py"            "--learning_rate 5e-7 --weight_decay 0.0"
submit_train "tis"             "train_gsm8k_offpolicy_tis.py"             "--learning_rate 5e-7"
submit_train "raft"            "train_gsm8k_offpolicy_raft.py"            "--learning_rate 5e-7" 16
submit_train "rloo"            "train_gsm8k_offpolicy_reinforce.py"       "--learning_rate 5e-7"
submit_train "naive-reinforce" "train_gsm8k_offpolicy_naive_reinforce.py" "--learning_rate 5e-7"

for NF in 0.0 0.2 0.4 0.6 0.8 1.0; do
  submit_train "tribe-negfrac${NF}" "train_gsm8k_offpolicy_tribe.py" \
    "--learning_rate 1e-7 --trust_region_eps 0.5 --divergence chi_squared --negative_fraction ${NF}"
done

dpo_jid=$(sbatch --parsable --gpus=2 --mem=240G --time=1-00:00:00 \
  --job-name="offpolicy-dpo-final-3b-gsm8k" \
  --output="${LOGDIR}/offpolicy-dpo-final-3b-gsm8k-%j.out" \
  --error="${LOGDIR}/offpolicy-dpo-final-3b-gsm8k-%j.err" \
  --export=ALL,TRAIN_CMD="accelerate launch --num_processes=2 --main_process_port=\$MASTER_PORT scripts/train_gsm8k_offpolicy_dpo.py --model_name_or_path ${MODEL} \
    --dataset_path ${DPO_DATASET} --output_dir ${OUTBASE}/dpo/gsm8k \
    --per_device_train_batch_size 4 --gradient_accumulation_steps 16 --learning_rate 5e-7 --beta 0.1 \
    --deepspeed configs/deepspeed_zero3.json --save_total_limit 1 --num_train_epochs 1 \
    --gradient_checkpointing --bf16 True --report_to wandb --run_name offpolicy-dpo-final-3b-gsm8k" \
  "$REPO_ROOT/slurm/run_experiment.sbatch")
echo -e "${dpo_jid}\tdpo\t${OUTBASE}/dpo/gsm8k\t${MODEL}" >> "$JOBLIST_FILE"
echo "submitted dpo: train=$dpo_jid"

simpo_jid=$(sbatch --parsable --gpus=2 --mem=240G --time=1-00:00:00 \
  --job-name="offpolicy-simpo-final-3b-gsm8k" \
  --output="${LOGDIR}/offpolicy-simpo-final-3b-gsm8k-%j.out" \
  --error="${LOGDIR}/offpolicy-simpo-final-3b-gsm8k-%j.err" \
  --export=ALL,TRAIN_CMD="$LAUNCH scripts/train_gsm8k_offpolicy_simpo.py --model_name_or_path ${MODEL} \
    --dataset_path ${DPO_DATASET} --output_dir ${OUTBASE}/simpo/gsm8k \
    --per_device_train_batch_size 4 --gradient_accumulation_steps 16 --learning_rate 5e-7 --beta 2.5 \
    --simpo_gamma 1.4 --lr_scheduler_type cosine \
    --save_total_limit 1 --num_train_epochs 1 \
    --gradient_checkpointing --bf16 True --report_to wandb --run_name offpolicy-simpo-final-3b-gsm8k" \
  "$REPO_ROOT/slurm/run_experiment.sbatch")
echo -e "${simpo_jid}\tsimpo\t${OUTBASE}/simpo/gsm8k\t${MODEL}" >> "$JOBLIST_FILE"
echo "submitted simpo: train=$simpo_jid"

echo "All 3B GSM8K jobs submitted. Job list written to $JOBLIST_FILE"
