# /// script
# dependencies = [
#     "trl",
# ]
# ///

"""
Offline RAFT (rejection-sampling SFT) baseline on GSM8K, off-policy / fully-offline (TOPR's
single-iteration regime, https://huggingface.co/papers/2503.14286): trains for ONE epoch over a FIXED
dataset pre-generated by scripts/generate_offpolicy_gsm8k.py (completions sampled once from the untrained
base model, never regenerated) — unlike every on-policy script in this suite, which generates fresh
rollouts every step.

Uses OffPolicyRaftTrainer (scripts/offpolicy_trainer.py): plain NLL on reward==1 examples only,
reward==0 examples dropped entirely (zero weight). No Stage 1, no mu/ratio, no frozen reference model —
the simplest possible baseline in this suite, for isolating how much of TRIBE/TOPR's improvement actually
comes from doing anything with the negative (incorrect) examples at all, versus just plain positive-only
SFT.

Subclasses plain transformers.Trainer (not GRPOTrainer/SFTTrainer) — see scripts/offpolicy_trainer.py's
own docstring for why. Model and tokenizer are loaded explicitly here (plain Trainer, unlike
GRPOTrainer/TribeTrainer, doesn't auto-load a model from a string name_or_path).

Usage:
python scripts/train_gsm8k_offpolicy_raft.py \
    --model_name_or_path Qwen/Qwen2.5-3B-Instruct \
    --dataset_path /scratch4/workspace/ychittepu_umass_edu-tribe/offpolicy-data/gsm8k \
    --output_dir offpolicy-raft-gsm8k-baseline \
    --group_size 16 \
    --per_device_train_batch_size 16 \
    --max_completion_length 512 \
    --learning_rate 5e-7 \
    --lr_scheduler_type constant \
    --gradient_checkpointing \
    --bf16 True
"""

from dataclasses import dataclass, field

import torch
from datasets import load_from_disk
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import ModelConfig, TrlParser, get_peft_config

from offpolicy_split import split_off_policy_dataset
from offpolicy_trainer import OffPolicyConfig, OffPolicyRaftTrainer


@dataclass
class OffPolicyScriptArguments:
    dataset_path: str = field(
        metadata={"help": "Path to the pre-generated dataset (scripts/generate_offpolicy_gsm8k.py's --output_dir)."}
    )
    max_positive_per_question: int | None = field(
        default=None,
        metadata={"help": "Caps reward==1 completions kept per question (ReST-EM/STaR use 10 for MATH). "
                  "None (default) keeps every positive completion, uncapped."},
    )


if __name__ == "__main__":
    parser = TrlParser((OffPolicyScriptArguments, OffPolicyConfig, ModelConfig))
    script_args, training_args, model_args = parser.parse_args_and_config()

    ################
    # Model
    ################
    dtype = model_args.dtype if model_args.dtype in ["auto", None] else getattr(torch, model_args.dtype)
    model = AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path,
        revision=model_args.model_revision,
        attn_implementation=model_args.attn_implementation,
        dtype=dtype,
    )
    peft_config = get_peft_config(model_args)
    if peft_config is not None:
        from peft import get_peft_model

        model = get_peft_model(model, peft_config)

    tokenizer = AutoTokenizer.from_pretrained(model_args.model_name_or_path)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    ################
    # Dataset
    ################
    dataset = load_from_disk(script_args.dataset_path)
    dataset = split_off_policy_dataset(dataset, training_args.group_size, training_args.val_fraction)

    ################
    # Training
    ################
    trainer = OffPolicyRaftTrainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
        processing_class=tokenizer,
        max_positive_per_question=script_args.max_positive_per_question,
    )

    trainer.train()

    trainer.save_model(training_args.output_dir)
    if training_args.push_to_hub:
        trainer.push_to_hub()
